# Generated by Django 6.0.2 on 2026-02-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_concept_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='knowledge_level',
            field=models.CharField(choices=[('zero', 'Zero Knowledge'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='zero', max_length=20),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='user_feedback',
            field=models.JSONField(default=dict),
        ),
    ]
