# Generated by Django 6.0.2 on 2026-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_error_history_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='break_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='consecutive_skips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='engagement_score',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='fatigue_level',
            field=models.CharField(default='fresh', max_length=20),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='last_break_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='velocity_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='retention_checks_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='retention_checks_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='retention_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='time_per_question',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='velocity_snapshots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
