# Generated by Django 6.0.2 on 2026-02-20 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userxp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited & Approved'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback on the question')),
                ('edited_question_text', models.TextField(blank=True)),
                ('edited_options', models.JSONField(blank=True, default=list)),
                ('edited_correct_index', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='accounts.question')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('target_mastery', models.FloatField(default=0.8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_class_wide', models.BooleanField(default=False, help_text='If true, applies to all students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.concept')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_goals', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reset_mastery', 'Reset Mastery'), ('assign_atom', 'Assign Specific Atom'), ('force_review', 'Force Review'), ('set_mastery', 'Set Mastery Level'), ('assign_remedial', 'Assign Remedial Content'), ('skip_atom', 'Skip Atom')], max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Action parameters (e.g., mastery value)')),
                ('reason', models.TextField(blank=True, help_text='Why the teacher is intervening')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='accounts.teachingatom')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='accounts.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_overrides', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_override',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_profile',
            },
        ),
        migrations.CreateModel(
            name='TeacherContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, help_text='Custom explanation for the atom')),
                ('analogy', models.TextField(blank=True, help_text='Custom analogy')),
                ('examples', models.JSONField(default=list, help_text='Custom examples')),
                ('tips', models.TextField(blank=True, help_text='Teaching tips for students')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('priority', models.BooleanField(default=True, help_text='If true, shown before AI content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_contents', to='accounts.teachingatom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_content',
                'ordering': ['-priority', '-updated_at'],
                'unique_together': {('teacher', 'atom')},
            },
        ),
    ]
