# Generated by Django 6.0.2 on 2026-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_questionapproval_teachergoal_teacheroverride_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
