# Generated by Django 6.0.2 on 2026-02-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacherprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogress',
            name='mastery_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='phase',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('diagnostic', 'Diagnostic'), ('teaching', 'Teaching'), ('practice', 'Practice'), ('reinforcement', 'Reinforcement'), ('mastery_check', 'Mastery Check'), ('complete', 'Complete'), ('fragile', 'Fragile')], default='not_started', max_length=20),
        ),
    ]
